/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testSmallPrime(){
        App appObj = new App();
        assertEquals(appObj.isPrime(17),true);
    }
    @Test
    public void testSmallNoPrime(){
        App appObj = new App();
        assertEquals(appObj.isPrime(33),false);
    }
    @Test
    public void testLargePrime(){
        App appObj = new App();
        assertEquals(appObj.isPrime(32416189049L),true);
    }
    @Test
    public void testLargeNoPrime(){
        App appObj = new App();
        assertEquals(appObj.isPrime(32416189051L),false);
    }

    @Test
    public void testCount1(){
        App appObj = new App();
        assertEquals(appObj.countPrime(0,0),0);
    }
    @Test
    public void testCount2(){
        App appObj = new App();
        assertEquals(appObj.countPrime(-1,1),2);
    }

    @Test
    public void testCount3(){
        App appObj = new App();
        assertEquals(appObj.countPrime(1,10),5);
    }
    @Test
    public void testCount4(){
        App appObj = new App();
        assertEquals(appObj.countPrime(20,40),4);
    }

}
